version: "3"
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-bun-app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://bunpostgresuser:bunpostgrespassword@db:5432/bunpostgresdb"
      NODE_ENV: "production"
    volumes:
      - .:/code:delegated

  db:
    image: postgres:14.1
    restart: always
    container_name: prisma-bun-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bunpostgresuser
      POSTGRES_PASSWORD: bunpostgrespassword
      POSTGRES_DB: bunpostgresdb
